title: How to MUDE?
author: MUDE from Delft University of Technology, built with <a href="https://teachbooks.io">TeachBooks</a> and <a href="https://jupyterbook.org/">Jupyter Book</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
logo: _static/MUDE_Logo-small.png

execute:
  execute_notebooks: "off"

only_build_toc_files: true

html:
  baseurl :  "https://tudelft-mude.github.io/teacher" #Replace this with your own URL

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_theme_options:
      logo:
        text: How to MUDE?
      repository_url: "https://github.com/TUDelft-MUDE/teacher" #add your own repo URL here
      path_to_docs: "book"
      repository_branch: "main"
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button : true
      launch_buttons:
        thebe: true
      named_colors_custom_colors: {'attributiongrey':[150,150,150]}
    html_show_copyright: false
    html_last_updated_fmt: '%B %-d, %Y'
    mathjax3_config:
      chtml: {
        mtextInheritFont: true # To typeset text within math prettier
      }
    tud_change_logo: false
  extra_extensions:
    - jupyterbook_patches
    - download_link_replacer
    - sphinx_image_inverter
    - sphinx_iframes
    - sphinx_exercise
    - sphinx_tudelft_theme
    - teachbooks_sphinx_tippy
    - sphinx_named_colors

bibtex_bibfiles: 
  - references.bib
